### ISSUE TITLE
Store my user name as well as other local config in some shared file

### ISSUE THREAD

**Issue by marktheunissen** [vole/vole#5]

**Comment by marktheunissen** [comment]
This is kicked off. Should we move my_user into this shared file?

**Comment by pifantastic** [comment]
Hmm, I tend to think the config file should be separate from any dynamic data. I don't mind the my_user file so much. It gives people the ability to hack a bit with their installation. Assuming people use read-only keys properly, they won't be able to do anything malicious.

**Comment by marktheunissen** [comment]
Ok cool! Agreed.
