### ISSUE TITLE
When unfollowing a user, its posts stays in your feed

### ISSUE THREAD

**Issue by daks** [vole/vole#56]
If you suscribe to user X, its posts goes on your 'timeline'. If you later unsuscribe they stays here.
I'm not sure this should be a wanted behaviour, but maybe it is

**Comment by marktheunissen** [comment]
Right now when you 'unsubscribe' or unfollow a user, you need to remove the shared folder in BitTorrent Sync and also delete the folder.

This should be implemented in the interface - one step to unfollow which does both - but this requires a BTSync API.

This will definitely be done. Thanks!

**Comment by daks** [comment]
Yes, I understand, it the same problem that the need to create the folder manually.
