### ISSUE TITLE
What is the goal of this project: a public social network or a mix of public/private one

### ISSUE THREAD

**Issue by daks** [vole/vole#59]
My question is:
- do vole wants to clone a public social network like twitter (which being public is the essence even if you can be private)
  or
- the possibility or having g+ like circles to class friends and share specific contents only with some groups of people, is one of the vole goal?

Having a decentralized public social network is good, but having a decentralized tool which can handle both public and private (with people groups) conversations would be really great!

**Comment by marktheunissen** [comment]
I think both use cases should be supported. It's up to the user if they want to share their key, and if they want to follow "public" profiles.

An interesting option is to have very trusted people all have read/write keys to the same folder - this opens up all sorts of possibilities.

**Comment by daks** [comment]
Not sure if I understand correctly your answer.
Of course I can imagine giving my key to only some specific people and in this case I'm in a 'private' configuration, but what I imagine (or search) is a tool which could do both: some posts can be public, some others limited to specific people groups, something like g+ or facebook functionality.
Does this seems possible with vole? At the moment I'm not sure.

**Comment by marktheunissen** [comment]
Yes, it would be possible using encryption. If each user places a public key in their folder, then others who want to send a private message to just that user, could use key to encrypt the message and place it in their shared folder. That allows two users who follow each other to send private messages. See https://github.com/vole/vole/issues/46

The next scenario, I could create a "group", and encrypt all messages to that group using a symmetric key. I can then share that key with certain people, so only those people can decrypt the messages, and thus read and reply to the messages.

I really hope we can use WebRTC to close the loop. At the moment, BitTorrent sync is one-way, people have read-only copies of your data. WebRTC can facilitate peer-to-peer communications between two people where only one person follows the other, or just to communicate information that is sensitive, for example the keys used in symmetric encryption.

All very possible and exciting!

**Comment by marktheunissen** [comment]
Made an issue for the .SyncIgnore: http://forum.bittorrent.com/topic/21284-syncignore-feature-request/
