### ISSUE TITLE
Cannot create profile: "Handler crashed with error runtime error:"

### ISSUE THREAD

**Issue by bortzmeyer** [vole/vole#68]
Ubuntu 13.04
Vole retrieved by git a few minutes ago
Go compiler in the Ubuntu package "go version go1.0.2"

% ./vole
2013/06/27 13:29:04 web.go serving 0.0.0.0:6789
2013/06/27 13:29:12 GET /
2013/06/27 13:29:12 GET /css/vendor/bootstrap.min.css
2013/06/27 13:29:12 GET /css/main.css
2013/06/27 13:29:12 GET /js/vendor/jquery.min.js
2013/06/27 13:29:12 GET /js/vendor/moment.min.js
2013/06/27 13:29:12 GET /js/plugins/jquery.moment.js
2013/06/27 13:29:12 GET /js/vendor/handlebars.js
2013/06/27 13:29:12 GET /js/vendor/bootstrap.min.js
2013/06/27 13:29:12 GET /js/vendor/ember-latest.js
2013/06/27 13:29:12 GET /js/vendor/ember-data-latest.js
2013/06/27 13:29:12 GET /js/vole.js
2013/06/27 13:29:13 GET /img/favicon.png
2013/06/27 13:29:13 GET /api/posts
2013/06/27 13:29:13 GET /api/users
...
2013/06/27 13:29:39 POST /api/users
2013/06/27 13:29:39 Handler crashed with error runtime error: invalid memory address or nil pointer dereference
2013/06/27 13:29:39 /build/buildd/golang-1.0.2/src/pkg/runtime/proc.c 1443
2013/06/27 13:29:39 /build/buildd/golang-1.0.2/src/pkg/runtime/runtime.c 128
2013/06/27 13:29:39 /build/buildd/golang-1.0.2/src/pkg/runtime/thread_linux.c 209
2013/06/27 13:29:39 /home/stephane/tmp/vole/src/lib/store/user.go 86
2013/06/27 13:29:39 /home/stephane/tmp/vole/src/lib/store/user.go 104
2013/06/27 13:29:39 /home/stephane/tmp/vole/src/vole/vole.go 121
2013/06/27 13:29:39 /usr/lib/go/src/pkg/reflect/value.go 521
2013/06/27 13:29:39 /usr/lib/go/src/pkg/reflect/value.go 334
2013/06/27 13:29:39 /home/stephane/tmp/vole/src/github.com/vole/web/server.go 196
2013/06/27 13:29:39 /home/stephane/tmp/vole/src/github.com/vole/web/server.go 305
2013/06/27 13:29:39 /home/stephane/tmp/vole/src/github.com/vole/web/server.go 87
2013/06/27 13:29:39 /home/stephane/tmp/vole/src/github.com/vole/web/server.go 82
2013/06/27 13:29:39 /usr/lib/go/src/pkg/net/http/server.go 926
2013/06/27 13:29:39 /usr/lib/go/src/pkg/net/http/server.go 656
2013/06/27 13:29:39 /build/buildd/golang-1.0.2/src/pkg/runtime/proc.c 271
2013/06/27 13:29:39 http: multiple response.WriteHeader calls

**Comment by mrjmad** [comment]
your go version is to old. You need use a earler version (1.1). ( vu que tu es français, j'ai écrit un mini manuel ici pour installer la dernière version de go : http://j-mad.com/blog/2013/06/26/manuel-rapide-dinstallation-de-vole-cc-sous-linux/ )

**Comment by marktheunissen** [comment]
Yes, Go 1.1+ required. Thanks.
