### ISSUE TITLE
Frequent refresh too CPU intensive

### ISSUE THREAD

**Issue by ilario** [vole/vole#75]
Vole _checks for new posts every second_.
This is a very _CPU intensive task_ and there's no need to check once a second.
So I suggest changing this line:
    static/js/vole.js:        setTimeout(refreshUI, 1000);
increasing refresh time, for example to 5 or 10 seconds.

**Comment by davidbgk** [comment]
Agreed, refreshing every second is way too much.

**Comment by pifantastic** [comment]
We're working towards switching to websockets. @elliotttf added websocket support to web.go here: https://github.com/vole/vole/pull/41

So hopefully polling won't be around much longer. In the mean time, I might be able to make the poll frequency configurable.

**Comment by marktheunissen** [comment]
I've made it configurable in the PR linked above.

**Comment by marktheunissen** [comment]
This should be working in master, please test and let us know. I've changed the default to 5 seconds and this is configurable in config.json. As @pifantastic says, we want to use websockets and have a PR almost ready. :shipit:
