### ISSUE TITLE
webRTC data api as an alternative to bittorrent sync

### ISSUE THREAD

**Issue by maxlath** [vole/vole#98]
Hi,

I saw your question here https://groups.google.com/forum/#!topic/golang-nuts/7WUj3nASuLo on how to base Vole on free software instead of BitTorrent Sync and I was woundering if webRTC data channel api could to the trick: isn't there a bright hack to do with what guys at ShareFest started? https://github.com/peer5/sharefest
(so far it only works between same-browser peers but it should be fix soon I guess)

btw, I can't make Vole work (nothing incredible as I'm just starting to get real on code): I compiled the current version myself as I'm using Linux Intel 32bits and get the logs hereafter when trying to create my profile
![capture du 2013-07-10 01 07 01](https://f.cloud.github.com/assets/1596934/771783/dba8f60c-e8ec-11e2-9267-1f48191be340.png)
anything known? shall I start a new issue dedicated to that?

Last, I would be glad to help translating Vole in French, do you plan to use http://transifex.com/ to coordinate transations or anything like this?

Best,

Maxime

**Comment by marktheunissen** [comment]
Hi Maxime,

What version of Go are you using? Try `go version`. You need 1.1+. If you're on the latest version of Go, maybe try `go clean` and then `make`? 

We have thought about WebRTC as the main data channel. It's very tempting, but it does make the application quite different. I think there are disadvantages to using WebRTC. I've wrote a bit about it here: https://github.com/vole/vole/issues/54#issuecomment-20084174. If you have any thoughts or comments on the pros/cons, I would love to hear them. I think WebRTC is an excellent choice for augmenting the application, I wrote up some thoughts on how WebRTC can be used to close the loop here: https://github.com/vole/vole/issues/59#issuecomment-20300294

And thank you for offering to translate! That's awesome. We are tracking ideas for internationalization here: #85.

**Comment by maxlath** [comment]
Thanks for your answer. Indeed, the problem was ubuntu default version of Go being Go1. I close this thread to eventually join the thread you pointed.
